from django.contrib import admin

from .models import User, Role, Category, Habit, Form, UserPlan, UserHabit, UserAchievement, Achievement, Task, Challenge, UserChallenge, UserTask, Level, UserStat, FormQuestion, UserAnswer, Advice, Guide, Favorite, Event, UserGroup

admin.site.register(Role)
admin.site.register(User)
admin.site.register(Category)
admin.site.register(Habit)
admin.site.register(Form)
admin.site.register(UserPlan)
admin.site.register(UserHabit)
admin.site.register(Achievement)
admin.site.register(UserAchievement)
admin.site.register(Challenge)
admin.site.register(Task)
admin.site.register(UserChallenge)
admin.site.register(UserTask)
admin.site.register(UserStat)
admin.site.register(Level)
admin.site.register(FormQuestion)
admin.site.register(UserAnswer)
admin.site.register(Advice)
admin.site.register(Guide)
admin.site.register(Favorite)
admin.site.register(Event)
admin.site.register(UserGroup)
