# Generated by Django 5.1.7 on 2025-03-23 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0010_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Эко-привычка')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('difficulty_level', models.PositiveIntegerField(verbose_name='Уровень сложности')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eco.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Эко-привычка',
                'verbose_name_plural': 'Эко-привычки',
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255, verbose_name='Цель')),
                ('status', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eco.form', verbose_name='Анкета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eco.habit', verbose_name='Эко-привычка')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eco.userplan', verbose_name='План')),
            ],
        ),
    ]
