# Generated by Django 5.1.7 on 2025-03-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0011_category_form_habit_userplan_userhabit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhabit',
            options={'verbose_name': 'Привычка пользователя', 'verbose_name_plural': 'Привычки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userplan',
            options={'verbose_name': 'План', 'verbose_name_plural': 'Планы'},
        ),
    ]
