# Generated by Django 5.1.7 on 2025-03-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0012_alter_userhabit_options_alter_userplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhabit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.userplan', verbose_name='План'),
        ),
    ]
