# Generated by Django 5.1.7 on 2025-03-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0013_alter_userhabit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhabit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='eco.userplan', verbose_name='План'),
        ),
    ]
