# Generated by Django 5.1.7 on 2025-03-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0016_challenge_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='tasks',
            field=models.ManyToManyField(to='eco.task', verbose_name='Задания'),
        ),
    ]
