# Generated by Django 5.1.7 on 2025-03-30 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0017_remove_task_challenge_challenge_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhabit',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.habit', verbose_name='Эко-привычка'),
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eco.challenge', verbose_name='Челлендж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eco.userchallenge', verbose_name='Челлендж')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eco.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Задание пользователя',
                'verbose_name_plural': 'Задания пользователей',
            },
        ),
    ]
