# Generated by Django 5.1.7 on 2025-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0021_formquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(to='eco.formquestion', verbose_name='Вопросы'),
        ),
    ]
