# Generated by Django 5.1.7 on 2025-04-05 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0024_advice_guide_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('afisha_image', models.ImageField(null=True, upload_to='events', verbose_name='Изображение для объявления')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('report', models.TextField(null=True, verbose_name='Отчет о прохождении')),
                ('report_image', models.ImageField(null=True, upload_to='reports', verbose_name='Изображение для отчета')),
                ('status', models.CharField(choices=[('A', 'Назначено'), ('R', 'Перенесено'), ('С', 'Завершено'), ('В', 'Отменено')], max_length=255, verbose_name='Статус мероприятия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
