# Generated by Django 5.1.7 on 2025-04-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0025_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
    ]
