# Generated by Django 5.1.7 on 2025-04-22 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0028_user_email_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
    ]
