# Generated by Django 5.1.7 on 2025-04-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0029_alter_user_email_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmation_token',
        ),
    ]
