# Generated by Django 5.1.7 on 2025-04-22 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0030_remove_user_email_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
