# Generated by Django 5.1.7 on 2025-04-23 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0031_alter_userstat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
    ]
