# Generated by Django 5.1.7 on 2025-04-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0032_user_email_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmation_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_confirmed',
        ),
    ]
