# Generated by Django 5.1.7 on 2025-04-28 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0033_remove_user_email_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='advice',
            name='is_posted',
            field=models.BooleanField(default=True, verbose_name='Выложен'),
        ),
    ]
