# Generated by Django 5.1.7 on 2025-04-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0034_advice_author_advice_is_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eco.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='icon',
            field=models.ImageField(null=True, upload_to='advices', verbose_name='Иконка совета'),
        ),
    ]
