# Generated by Django 5.1.7 on 2025-05-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0037_groupmember_usergroup_groupmember_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='users',
        ),
    ]
