# Generated by Django 5.1.7 on 2025-05-04 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0039_alter_groupmember_group_alter_groupmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='eco.usergroup', verbose_name='Группа'),
        ),
    ]
