# Generated by Django 5.1.7 on 2025-05-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0040_alter_groupmember_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='author',
        ),
    ]
