# Generated by Django 5.1.7 on 2025-05-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0041_remove_advice_author'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE VIRTUAL TABLE IF NOT EXISTS advice_search USING fts5(
                title,
                description,
                content='eco_advice',
                content_rowid='id'
            );
            """,
            """
            DROP TABLE IF EXISTS advice_search;
            """
        ),
    ]
