# Generated by Django 5.1.7 on 2025-05-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0047_auto_20250506_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='annotation',
            field=models.TextField(null=True, verbose_name='Важное'),
        ),
    ]
