# Generated by Django 5.1.7 on 2025-05-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0048_guide_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_posted',
            field=models.BooleanField(default=True, verbose_name='Выложен'),
        ),
    ]
