# Generated by Django 5.1.7 on 2025-05-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0050_guide_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='this_week',
            field=models.BooleanField(default=False, verbose_name='Челлендж недели'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='this_week_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
