# Generated by Django 5.1.7 on 2025-05-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0051_challenge_this_week_challenge_this_week_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eco.achievement', verbose_name='Награда'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eco.category', verbose_name='Категория'),
        ),
    ]
