# Generated by Django 5.1.7 on 2025-05-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0052_alter_challenge_achievement_alter_challenge_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(null=True, upload_to='achievements', verbose_name='Иконка награды'),
        ),
    ]
