# Generated by Django 5.1.7 on 2025-05-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0053_alter_achievement_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='want_organization',
            field=models.BooleanField(default=False, verbose_name='Заявка на организацию'),
        ),
    ]
