# Generated by Django 5.1.7 on 2025-05-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0054_user_want_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='this_day',
            field=models.BooleanField(default=False, verbose_name='Привычка недели'),
        ),
    ]
