# Generated by Django 5.1.7 on 2025-05-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0055_habit_this_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип хранилища')),
                ('record', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tasks',
            field=models.ManyToManyField(related_name='challenges', to='eco.task', verbose_name='Задания'),
        ),
    ]
