# Generated by Django 5.1.7 on 2025-05-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0056_vectorstore_alter_challenge_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eco.userchallenge', verbose_name='Челлендж'),
        ),
    ]
