# Generated by Django 5.1.7 on 2025-05-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0057_alter_usertask_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='tasks',
            field=models.ManyToManyField(to='eco.task', verbose_name='Задания'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='eco.userchallenge', verbose_name='Челлендж'),
        ),
    ]
