# Generated by Django 5.1.7 on 2025-05-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0058_alter_challenge_tasks_alter_usertask_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eco.category', verbose_name='Категория'),
        ),
    ]
